#!/usr/bin/env node
import "dotenv/config";
import { createInterface } from "readline";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { printSetupWelcome, printSetupComplete, section, success, info, warn, divider, c, sleep } from "./ui.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = join(__dirname, "../.env");

function ask(rl, q) {
  return new Promise(r => rl.question("  " + c.mint("›") + "  " + q + " ", r));
}

function askChoice(rl, question, choices) {
  return new Promise(r => {
    console.log("  " + c.white(question));
    console.log("");
    choices.forEach((ch, i) => console.log("  " + c.muted(`  ${i + 1}.`) + "  " + c.white(ch)));
    console.log("");
    rl.question("  " + c.mint("›") + "  " + c.muted("Choice: "), (ans) => {
      const idx = parseInt(ans) - 1;
      r(idx >= 0 && idx < choices.length ? idx : 0);
    });
  });
}

async function setupAgent(rl, name, emoji, keyUrl, config) {
  divider();
  section(emoji, name);
  const mode = await askChoice(rl, `How do you want to connect ${name}?`, [
    `My own API key  ${c.muted("(free, use your account)")}`,
    `Skip for now`,
  ]);
  if (mode === 0) {
    info(`Get your key at: ${keyUrl}`);
    console.log("");
    const key = (await ask(rl, `${name} API Key ${c.muted("(Enter to skip)")}: `)).trim();
    config.apiKey = key;
    config.enabled = !!key;
    if (key) success(`${name} connected`);
    else warn(`${name} skipped`);
  } else {
    config.enabled = false;
    warn(`${name} skipped — add later in .env`);
  }
}

async function main() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  printSetupWelcome();
  await sleep(400);

  const config = { telegram: {}, claude: {}, chatgpt: {}, gemini: {}, netlify: {} };

  // Telegram
  divider();
  section("📱", "Telegram Bot");
  console.log("  " + c.muted("1. Open Telegram → search ") + c.mint("@BotFather"));
  console.log("  " + c.muted("2. Send ") + c.white("/newbot") + c.muted(" and follow the steps"));
  console.log("  " + c.muted("3. Copy the token it gives you"));
  console.log("");
  config.telegram.token = (await ask(rl, "Telegram Bot Token: ")).trim();
  if (config.telegram.token) success("Telegram bot connected");
  else warn("No Telegram token — bot won't start");

  // Claude
  await setupAgent(rl, "Claude", "🟡", "console.anthropic.com → API Keys", config.claude);

  // ChatGPT
  await setupAgent(rl, "ChatGPT", "🟢", "platform.openai.com/api-keys", config.chatgpt);

  // Gemini
  await setupAgent(rl, "Gemini", "🔵", "aistudio.google.com/app/apikey", config.gemini);

  // Netlify
  divider();
  section("🌐", "Netlify — Deploy Engine");
  console.log("  " + c.muted("1. Go to ") + c.mint("app.netlify.com/user/applications"));
  console.log("  " + c.muted("2. Personal access tokens → New access token"));
  console.log("  " + c.muted("3. Name it 'openkrew' → Generate → Copy"));
  console.log("");
  const netlifyToken = (await ask(rl, `Netlify Token ${c.muted("(Enter to skip)")}: `)).trim();
  config.netlify.token = netlifyToken;
  config.netlify.enabled = !!netlifyToken;
  if (netlifyToken) success("Netlify connected — permanent URLs enabled!");
  else warn("Netlify skipped — deploys won't work without it");

  rl.close();

  // Write .env
  const lines = [
    "# OpenKrew config — generated by setup wizard",
    "",
    `TELEGRAM_BOT_TOKEN=${config.telegram.token || ""}`,
    "",
    config.claude.apiKey    ? `ANTHROPIC_API_KEY=${config.claude.apiKey}`   : "# ANTHROPIC_API_KEY=",
    config.chatgpt.apiKey   ? `OPENAI_API_KEY=${config.chatgpt.apiKey}`     : "# OPENAI_API_KEY=",
    config.gemini.apiKey    ? `GEMINI_API_KEY=${config.gemini.apiKey}`      : "# GEMINI_API_KEY=",
    config.netlify.token    ? `NETLIFY_TOKEN=${config.netlify.token}`       : "# NETLIFY_TOKEN=",
  ];

  writeFileSync(ENV_PATH, lines.join("\n"));

  const active = [];
  if (config.claude.enabled)  active.push("claude");
  if (config.chatgpt.enabled) active.push("chatgpt");
  if (config.gemini.enabled)  active.push("gemini");
  if (config.netlify.enabled) active.push("netlify");

  printSetupComplete(active.length > 0 ? active : ["none"]);
}

main().catch(e => { console.error(e); process.exit(1); });
